export const APP_CONSTANTS = {
    URL_GET_CATEGORIES: 'https://api.quanaudio.vn/get-menu-types',
    URL_GET_SLIDE: 'https://api.quanaudio.vn/get-slides',
    URL_GET_AUDIO: 'https://api.quanaudio.vn/get-audios',
    URL_GET_DETAIL_AUDIO: 'https://api.quanaudio.vn/get-audio',
    URL_GET_AUDIOS: 'https://api.quanaudio.vn/get-cart-items',
    URL_GET_AUDIO_BY_TYPE: 'https://api.quanaudio.vn/get-audio-by-type',
    URL_POST_CHECKOUT: 'https://api.quanaudio.vn/api_dev.php/post-checkout',
    URL_GET_LATEST_NEWS : 'https://api.quanaudio.vn/get-latest-news',
    URL_GET_DETAIL_NEW : 'https://api.quanaudio.vn/get-detail-new',
    URL_GET_RANDOM_NEW : 'https://api.quanaudio.vn/get-random-new',
    KEY_CART: 'CART',
    TIME_OUT: 3600000,
    APPEND_LOCALSTORAGE: 'APPEND_STORAGE',
    CREATE_NEW_LOCALSTORAGE: 'CREATE_NEW_STORAGE',
    DELETE_ITEM_LOCALSTORAGE: 'DELETE_ITEM_STORAGE',
    SET_LOCALSTORAGE: 'RESET_STORAGE',
    TIN_TUC: 'TINTUC',
    CONG_TRINH_HOAN_THANH: 'CTHT',
    URL_TIN_TUC: 'https://api.quanaudio.vn/tin-tuc',
    PREFIX_URL_ADMIN: 'admin'
}